caraml-store-registry/src/main/java/dev/caraml/store/sparkjob/JobService.java

Currently, ListJobs failed due to the job type not being present in the response object.

Fix list jobs API

---

caraml-store-registry/src/main/java/dev/caraml/store/sparkjob/JobService.java
caraml-store-registry/src/test/java/dev/caraml/store/sparkjob/JobServiceTest.java

Kubernetes has a maximum character limit of 63 for labels.

Use hash for job filter and truncate label

---

caraml-store-serving/src/main/java/dev/caraml/serving/store/bigtable/BigTableStoreConfig.java
caraml-store-serving/src/main/java/dev/caraml/serving/store/redis/RedisClient.java
caraml-store-serving/src/main/java/dev/caraml/serving/store/redis/RedisClusterStoreConfig.java
caraml-store-serving/src/main/java/dev/caraml/serving/store/redis/RedisStoreConfig.java
caraml-store-serving/src/main/resources/application.yaml

Currently it's not possible to overwrite the store configuration to use stores other than default unless the application.yaml resource is not in the configuration path. Similar with tcp config and topology refresh configuration.

Fix store configuration

---

caraml-store-serving/build.gradle

The current version of bigtable client uses an older version of grpc-auth, which is incompatible with other dependencies.

Update bigtable client

---

caraml-store-serving/src/main/java/dev/caraml/serving/featurespec/CacheProperties.java
caraml-store-serving/src/main/java/dev/caraml/serving/featurespec/FeatureSpecService.java
caraml-store-serving/src/main/resources/application.yaml
caraml-store-serving/src/test/java/dev/caraml/serving/featurespec/FeatureSpecServiceTest.java

Cache refresh is not scheduled to run periodically as it is supposed to be.

Schedule populate cache job

---

caraml-store-pyspark/requirements.txt
caraml-store-pyspark/scripts/historical_feature_retrieval_job.py
caraml-store-pyspark/templates/extract_timestamps.jinja2
caraml-store-pyspark/templates/retrieval.jinja2
caraml-store-pyspark/tests/test_historical_feature_retrieval.py
caraml-store-spark/docker/Dockerfile

In scenarios where entity source and all feature table sources are from BigQuery, we can delegate the historical retrieval job to BQ instead for better cost efficiency.

Delegate historical retrieval task to BigQuery if feasible

---

caraml-store-python/setup.py

The existing python requirement is overly strict and can be relaxed.

Remove strict version requirement for dependencies

---

caraml-store-serving/src/main/java/dev/caraml/serving/store/StoreService.java

In situation where the entity rows is empty, it negatively impact the BigTable retrieval latency unless we capture this early and throw exception.

Return error when entity rows is empty

---

caraml-store-serving/src/main/java/dev/caraml/serving/store/bigtable/BigTableStoreConfig.java
caraml-store-serving/src/main/resources/application.yaml

Allow user to set timeout for bigtable client. By default, the default behaviour of the BigTable client applies.

Add support for timeout for BigTable retrieval

---

caraml-store-serving/src/main/java/dev/caraml/serving/CaraMLServing.java
caraml-store-serving/src/main/java/dev/caraml/serving/store/StoreService.java
caraml-store-serving/src/main/resources/application.yaml

Feature cache is currently not being refreshed and only loaded once during start up, which means feature update is not being picked up by the serving service.

fix: enable scheduling for feature cache refresh

---

caraml-store-serving/src/main/java/dev/caraml/serving/featurespec/FeatureSpecService.java

The initial delay string expression was incorrect resulting in crash during start up.

fix: incorrect initial delay string expression

---

caraml-store-serving/src/main/java/dev/caraml/serving/store/bigtable/BigTableOnlineRetriever.java

BigTable rowCell getTimestamp returns the timestamp as microseconds since epoch, instead of milliseconds as it was assumed in the original implementation.

fix: fix bigtable max age calculation

---

caraml-store-serving/src/main/java/dev/caraml/serving/monitoring/MonitoringConfig.java
caraml-store-serving/src/main/java/dev/caraml/serving/monitoring/ServingMetrics.java
caraml-store-serving/src/main/resources/application.yaml

Add entity count distribution metric

feat: add entity count distribution

---

.gitignore
caraml-store-spark/build.gradle
caraml-store-spark/src/main/scala/dev/caraml/spark/BasePipeline.scala
caraml-store-spark/src/main/scala/dev/caraml/spark/IngestionJobConfig.scala
caraml-store-spark/src/main/scala/dev/caraml/spark/stores/redis/RedisSinkRelation.scala
caraml-store-spark/src/test/scala/dev/caraml/spark/BatchPipelineSpec.scala
caraml-store-spark/src/test/scala/dev/caraml/spark/StreamingPipelineSpec.scala

Allow write ops to Redis sink to be rate limited using Bucket4j library.

feat: Add support for local rate limiter

---

caraml-store-spark/src/main/scala/dev/caraml/spark/stores/redis/RateLimiter.scala
caraml-store-spark/src/main/scala/dev/caraml/spark/stores/redis/RedisSinkRelation.scala

Currently, the rate limiter bucket will be instantiated more than once in the presence of multiple partition. We will use singleton pattern instead to make sure that only one limiter is created per executor.

fix: use singleton rate limiter 

---

caraml-store-registry/src/main/java/dev/caraml/store/sparkjob/crd/SparkDriverSpec.java
caraml-store-registry/src/main/java/dev/caraml/store/sparkjob/crd/SparkExecutorSpec.java
caraml-store-registry/src/test/java/dev/caraml/store/sparkjob/JobServiceTest.java

Adding support of additional fields on SparkApplication CRD:
* `memoryOverhead`
* `coreLimit`
[Reference](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/api-docs.md#sparkoperator.k8s.io/v1beta2.SparkPodSpec)
Support of these fields would provide better control over scheduling of ingestion jobs on k8s cluster.

feat(registry): Add support of memoryOverhead and coreLimit for Spark jobs

---

caraml-store-sdk/python/setup.py

Updating the `protobuf` dependency of the Python SDK to let it be used with protobuf version 3.

Relax Python SDK protobuf dependency

---

caraml-store-sdk/python/feast/gcp/staging.py

Running the utils function `stage_entities_to_bq` concurrently may potentially cause BigQuery tables created to share the same timestamp, up to the second. This will cause data to be appended to the same table unexpected and/or cause other concurrent runs to get a `"Precondition check failed" 412 PATCH bigquery update_table` error from BigQuery as the table they are supposed to write to is changed unexpectedly (by another concurrent run) before the write job begins.
The fix introduced simply replaces the timestamp in the table name created with a uuid.

chore: Replace timestamp in staged bigquery table name with uuid

---

caraml-store-pyspark/scripts/historical_feature_retrieval_job.py

Historical retrieval job often fails when the size of the entities are larger than what broadcast join can handle. The original intention of using broadcast join is to speed up the computation, assuming that the entities are small enough to be broadcasted, but that is rarely the case. It's also unclear at the moment on how much is the performance gain we can attain by using broadcast join.
Until more research is performed, we will disable broadcast join by default.

feat: disable broadcast join

---

caraml-store-registry/src/main/java/dev/caraml/store/mlp/Label.java
caraml-store-registry/src/main/java/dev/caraml/store/mlp/Project.java
caraml-store-registry/src/main/java/dev/caraml/store/mlp/ProjectContextProvider.java
caraml-store-registry/src/main/java/dev/caraml/store/sparkjob/JobTemplateRenderer.java
caraml-store-registry/src/test/java/dev/caraml/store/sparkjob/JobTemplateRendererTest.java

* caraml-store-registry does not apply MLP project `labels` 
* This PR modifies the renderer to substitute the values of labels found in the configuration that were not found in MLP project `labels` field.

feat: Apply project labels from MLP

---

buildSrc/src/main/groovy/caraml.common.gradle
caraml-store-registry/src/main/java/dev/caraml/store/CaraMLRegistry.java

Scheduling wasn't enabled on CaraML Registry service, which resulted in MLP project cache not being refreshed as intended.
Also fixed a bug where the version is not properly determined due to mistake in regex.

Enable scheduling for caraml store registry

---

caraml-store-serving/build.gradle
caraml-store-spark/build.gradle

- Upgrade dependency Google Big Table: 2.19.1 -> [2.40.0](https://cloud.google.com/java/docs/reference/google-cloud-bigtable/latest/history#2400httpsgithubcomgoogleapisjava-bigtablecomparev2395v2400-2024-06-28) (2024-06-28)
- Upgrade dependency bigtable-hbase-2.x-hadoop: 1.26.3 -> [2.14.3](https://mvnrepository.com/artifact/com.google.cloud.bigtable/bigtable-hbase-2.x-hadoop/2.14.3) (2024-06-30)

Upgrade Google BigTable client

---

caraml-store-serving/build.gradle
caraml-store-serving/src/main/java/dev/caraml/serving/store/bigtable/BaseSchemaRegistry.java
caraml-store-serving/src/main/java/dev/caraml/serving/store/bigtable/BigTableOnlineRetriever.java
caraml-store-serving/src/main/java/dev/caraml/serving/store/bigtable/BigTableSchemaRegistry.java
caraml-store-serving/src/main/java/dev/caraml/serving/store/bigtable/BigTableStoreConfig.java
caraml-store-serving/src/main/java/dev/caraml/serving/store/bigtable/HBaseOnlineRetriever.java
caraml-store-serving/src/main/java/dev/caraml/serving/store/bigtable/HBaseSchemaRegistry.java
caraml-store-serving/src/main/java/dev/caraml/serving/store/bigtable/HBaseStoreConfig.java
caraml-store-serving/src/main/resources/application.yaml
caraml-store-serving/src/test/java/dev/caraml/serving/store/bigtable/BigTableOnlineRetrieverTest.java
caraml-store-serving/src/test/java/dev/caraml/serving/store/bigtable/GenericHbase2Container.java
caraml-store-serving/src/test/java/dev/caraml/serving/store/bigtable/HbaseOnlineRetrieverTest.java
caraml-store-spark/docker/Dockerfile
caraml-store-spark/src/main/scala/dev/caraml/spark/BasePipeline.scala
caraml-store-spark/src/main/scala/dev/caraml/spark/BatchPipeline.scala
caraml-store-spark/src/main/scala/dev/caraml/spark/IngestionJob.scala
caraml-store-spark/src/main/scala/dev/caraml/spark/IngestionJobConfig.scala
caraml-store-spark/src/main/scala/dev/caraml/spark/StreamingPipeline.scala
caraml-store-spark/src/main/scala/dev/caraml/spark/stores/bigtable/BigTableSinkRelation.scala
caraml-store-spark/src/main/scala/dev/caraml/spark/stores/bigtable/DefaultSource.scala
caraml-store-spark/src/main/scala/dev/caraml/spark/stores/bigtable/HbaseSinkRelation.scala

This PR adds support to use hbase as the online store.
- Read data from BigTable and Hbase in caraml-serving by using HBase SDK by set configuration `caraml.store.bigtable.isUsingHBaseSDK` become `true`. If the value is `false`, then it will read data by using BigTable SDK.
- Modifies spark job to ingest the data into HBase for stream and batch ingestion, but reuses most of the existing logic to pull data from BigTable.
- Add additional unit tests to read data from bigtable using HBase sdk, and to read data from hbase directly
- Refactor bigtable online store to share BaseSchemaRegistry

feat: add HBase SDK for serving

---

caraml-store-spark/src/main/scala/dev/caraml/spark/StreamingPipeline.scala
caraml-store-spark/src/test/scala/dev/caraml/spark/StreamingPipelineSpec.scala

- Enable streaming ingestion jobs to read topics using `subscribePattern` instead of `subscribe`
- This is only supported in the spark job, topics in the feature table data source should specify exact topic

feat: Set subscribe pattern to wildcard prefix

---

.github/workflows/odps.yaml
caraml-store-spark/build.gradle
caraml-store-spark/src/main/scala/dev/caraml/spark/odps/CustomDialect.scala

* Add CustomDialect class for odps <> spark connectivity via jdbc format
* The methods overridden are so that the SQL queries that spark generates are compatible with odps (ie odps can run those queries)
* Add workflow and modify github gradle to create a draft release of the custom-dialect jar so that merlin / caraml-store can use it

feat: add source and build for custom dialect

---

.github/workflows/sdk_release.yaml

Using ubuntu-latest as base image to generate sdk release/push to pypi doesn't work with python3.7 version 
The pipeline - https://github.com/caraml-dev/caraml-store/actions/runs/13362528259
The discussion - https://github.com/actions/setup-python/issues/962
Tested and worked - https://github.com/caraml-dev/caraml-store/actions/runs/13363489867/job/37316971422
To fix, using ubuntu-22.04 helps resolve the issue

update python version of gitlab runner for sdk release

---

caraml-store-spark/src/main/scala/dev/caraml/spark/sources/maxCompute/MaxComputeReader.scala

The MaxCompute reader retrieves the event_time_stamp column as epoch time by converting it using to_millis() and then querying the records. However, this approach bypasses the automatically created partitions, causing the queries to fail.
Using Spark to filter records by timestamp isn't a viable option because it does not utilize the auto-partitioning. Spark loads the entire table into memory before applying filters, which bypasses the partitioning mechanism.
This PR - reads the records by casting the datetime to a timestamp using MaxCompute's CAST() function. This allows the filtering of records while also leveraging the auto-partitioning feature.

modify maxcompute reader jdbc query to use partition

---

caraml-store-spark/src/main/scala/dev/caraml/spark/sources/maxCompute/MaxComputeReader.scala

- This PR modifies the sqlQuery used in MaxComputerReader class so that the outcome matches the expression used in BigQueryReader -
```
reader
.load(s"${source.project}.${source.dataset}.${source.table}")
.filter(col(source.eventTimestampColumn) >= new Timestamp(start.getMillis))
.filter(col(source.eventTimestampColumn) < new Timestamp(end.getMillis))
}
```
This issue was raised when users ingested the same data from bigquery and maxcompute but found that the data in the online store was different.

fix: query used in MaxComputeReader

---

caraml-store-spark/src/main/scala/dev/caraml/spark/BatchPipeline.scala
caraml-store-spark/src/main/scala/dev/caraml/spark/IngestionJob.scala
caraml-store-spark/src/main/scala/dev/caraml/spark/IngestionJobConfig.scala
caraml-store-spark/src/main/scala/dev/caraml/spark/sources/maxCompute/MaxComputeReader.scala

* This PR moves maxcompute jdbc configurations into it's own case class and parses them in as command line arguments
* Adds default autoSelectLimit of 1,000,000,000 rows, see maxcompute [docs](https://www.alibabacloud.com/help/en/maxcompute/user-guide/maxcompute-query-acceleration) for more info
* Add debug option to print rows read from source and pushed to sink
* Format code

feat: Modify maxcompute configs to be parsable from command line

---

caraml-store-registry/src/main/java/dev/caraml/store/sparkjob/adapter/DataSourceConverter.java
caraml-store-registry/src/test/java/dev/caraml/store/sparkjob/adapter/DataSourceConverterTest.java
caraml-store-sdk/python/feast/maxcompute/staging.py
caraml-store-sdk/python/requirements-ci.txt
caraml-store-sdk/python/setup.py

* This MR adds a helper function to stage entities to maxcompute 
* Allows both `project.schema.table` and `project:schema.table` format for maxcompute datasources
* Add pyodps package as caraml-store-sdk dependency

feat: stage entities to maxcompute utility, modify accepted format for mc datasource

---

.github/workflows/sdk_release.yaml

* Bump github action versions
* Use python 3.8 instead of 3.7
* Tested sdk_release pipeline [here](https://github.com/caraml-dev/caraml-store/actions/runs/14570394333/job/40866478270?pr=143)

Fix sdk_release pipeline

---

caraml-store-registry/src/main/java/dev/caraml/store/feature/FeatureTable.java
caraml-store-registry/src/main/java/dev/caraml/store/feature/RegistryConfig.java
caraml-store-registry/src/main/java/dev/caraml/store/feature/RegistryService.java
caraml-store-registry/src/main/resources/application.yaml
caraml-store-registry/src/test/java/dev/caraml/store/api/RegistryGrpcServiceIT.java
caraml-store-registry/src/test/java/dev/caraml/store/sparkjob/JobServiceTest.java
caraml-store-registry/src/test/resources/application-it.yaml
caraml-store-testutil/src/main/java/dev/caraml/store/testutils/it/DataGenerator.java

Summary:
- added new config featureTableDefaultMaxAgeSeconds
- use defaultMaxAge in feature-table creation in case maxAge is not provided
- use last set maxAge if feature-table update is provided with maxAge

feat: use default max age when max_age is not provided

---

caraml-store-spark/src/main/scala/dev/caraml/spark/BatchPipeline.scala

* Previously, if debug was enabled, 2 copies would be persisted in memory
* This usually results in the executor being oomkilled
* This mr fixes this by removing the persist() method call for validRows. The result is that 2 calls to the data source (ie maxcompute / bigquery) will be run to fetch the data when debug mode is enabled. This should be acceptable as we are running --debug mode only to resolve errors / during development and not in production.

fix: do not persist validRows when debug is enabled

---

caraml-store-spark/src/main/scala/dev/caraml/spark/BasePipeline.scala
caraml-store-spark/src/main/scala/dev/caraml/spark/IngestionJob.scala
caraml-store-spark/src/main/scala/dev/caraml/spark/IngestionJobConfig.scala
caraml-store-spark/src/main/scala/dev/caraml/spark/sources/maxCompute/MaxComputeReader.scala

- improve logging in spark job
- add jdbc partitioning options, to partition by event timestamp column and use start date and end date as partition boundary
- add `alwaysFallback=true` parameter so switch to offline mode for queries that involve large tables

Improve batch ingestion pipeline
